<?php
declare(strict_types=1);
require_once is_file(__DIR__ . '/src/bootstrap.php') ? __DIR__ . '/src/bootstrap.php' : dirname(__DIR__) . '/src/bootstrap.php';
session_start();
header('X-Robots-Tag: noindex, nofollow, noarchive', true);
if (empty($_SESSION['admin_authenticated'])) { header('Location: ' . url('admin.php')); exit; }

function teamAdminText(string $name): string { return trim((string) ($_POST[$name] ?? '')); }
function teamAdminList(string $name): array { $parts=preg_split('/[\r\n,、]+/u',teamAdminText($name))?:[]; return array_values(array_unique(array_filter(array_map('trim',$parts)))); }
function teamAdminListText(array $values): string { return implode(PHP_EOL,array_map('strval',$values)); }

$repo=repository('teams'); $teams=$repo->all(); $error=''; $notice=''; $selectedId=(string)($_GET['id']??''); $team=$selectedId!==''?findById($teams,$selectedId):null;
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['save_team'])) {
    try {
        if (!hash_equals((string)($_SESSION['csrf_token']??''),(string)($_POST['csrf_token']??''))) throw new RuntimeException('セッションの有効期限が切れました。再読み込みしてください。');
        $id=teamAdminText('id'); $existing=findById($teams,$id); if($existing===null)throw new InvalidArgumentException('編集対象の作品が見つかりません。');
        $required=['team_name'=>'チーム名','game_name'=>'作品名','genre'=>'ジャンル','players'=>'プレイ人数','engine'=>'使用エンジン','production_period'=>'制作期間','booth_no'=>'ブース番号','catchcopy'=>'キャッチコピー','description'=>'作品説明'];
        $values=[]; foreach($required as $key=>$label){$values[$key]=teamAdminText($key);if($values[$key]==='')throw new InvalidArgumentException($label.'を入力してください。');}
        $video=teamAdminText('video_url'); if($video!==''&&(filter_var($video,FILTER_VALIDATE_URL)===false||preg_match('~^https?://~i',$video)!==1))throw new InvalidArgumentException('動画URLを正しく入力してください。');
        $team=['id'=>$id,'team_name'=>$values['team_name'],'game_name'=>$values['game_name'],'genre'=>$values['genre'],'players'=>$values['players'],'platforms'=>teamAdminList('platforms'),'engine'=>$values['engine'],'production_period'=>$values['production_period'],'booth_no'=>$values['booth_no'],'catchcopy'=>$values['catchcopy'],'description'=>$values['description'],'highlights'=>teamAdminList('highlights'),'controls'=>teamAdminList('controls'),'screenshots'=>$existing['screenshots']??[],'theme'=>teamAdminText('theme')?:'red','video_url'=>$video];
        $repo->saveById($team,false);
        syncManagedQr('team-'.$id,'作品：'.$team['game_name'],absoluteUrl('team_detail.php',['id'=>$id]),true);
        header('Location: '.url('teams_admin.php').'?id='.rawurlencode($id).'&saved=1'); exit;
    } catch(Throwable $exception){$error=$exception->getMessage();}
}
if(isset($_GET['saved']))$notice='作品データとQRコードを保存しました。';
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>作品データ管理 | TGS SCOUT ADMIN</title><link rel="stylesheet" href="<?= e(url('assets/style.css')) ?>"><link rel="stylesheet" href="<?= e(url('assets/qr-admin.css')) ?>"></head><body class="admin-body"><main class="admin-main"><section class="admin-shell">
<div class="admin-toolbar"><div><p class="section-number">TGS SCOUT ADMIN</p><h1>作品データ管理</h1><p class="admin-lead">作品情報の更新とQRコード作成</p></div><div class="admin-toolbar-actions"><a class="button button-outline" href="<?= e(url()) ?>">← 公開ページへ</a><form method="post" action="<?= e(url('admin.php')) ?>"><button class="button button-primary" name="logout" value="1">ログアウト</button></form></div></div>
<nav class="admin-tabs"><a href="<?= e(url('admin.php')) ?>">学生</a><a href="<?= e(url('admin.php')) ?>?section=featured">注目学生</a><a class="is-active" href="<?= e(url('teams_admin.php')) ?>">作品</a><span>所属関係 <small>準備中</small></span></nav>
<?php if($notice):?><p class="admin-success"><?=e($notice)?></p><?php endif;?><?php if($error):?><p class="admin-error" role="alert"><?=e($error)?></p><?php endif;?>
<div class="admin-grid"><aside class="admin-list"><div class="admin-list-head"><strong>登録作品</strong><span><?=count($teams)?>件</span></div><?php foreach($teams as $item):?><a class="<?= $selectedId===($item['id']??'')?'is-current':''?>" href="<?=e(url('teams_admin.php'))?>?id=<?=e($item['id'])?>"><span><strong><?=e($item['game_name'])?></strong><small><?=e($item['team_name'])?></small></span><span class="admin-status is-public">公開</span></a><?php endforeach;?></aside>
<div class="admin-editor"><?php if($team!==null):$teamQrUrl=managedQrUrl('team-'.$team['id']);?><div class="admin-editor-head"><div><p class="section-number">EDIT WORK</p><h2><?=e($team['game_name'])?></h2></div><span>必須項目 <b>*</b></span></div><form method="post" class="admin-student-form"><input type="hidden" name="csrf_token" value="<?=e($_SESSION['csrf_token'])?>"><input type="hidden" name="id" value="<?=e($team['id'])?>">
<fieldset><legend><span>01</span>基本情報</legend><div class="admin-form-grid"><label>作品名 <b>*</b><input name="game_name" value="<?=e($team['game_name'])?>" required></label><label>チーム名 <b>*</b><input name="team_name" value="<?=e($team['team_name'])?>" required></label><label>ジャンル <b>*</b><input name="genre" value="<?=e($team['genre'])?>" required></label><label>プレイ人数 <b>*</b><input name="players" value="<?=e($team['players'])?>" required></label><label>対応機種<textarea name="platforms" rows="3"><?=e(teamAdminListText($team['platforms']))?></textarea></label><label>使用エンジン <b>*</b><input name="engine" value="<?=e($team['engine'])?>" required></label><label>制作期間 <b>*</b><input name="production_period" value="<?=e($team['production_period'])?>" required></label><label>ブース番号 <b>*</b><input name="booth_no" value="<?=e($team['booth_no'])?>" required></label><label>テーマ<select name="theme"><?php foreach(['red','navy','yellow'] as $theme):?><option value="<?=e($theme)?>" <?=($team['theme']??'')===$theme?'selected':''?>><?=e($theme)?></option><?php endforeach;?></select></label></div></fieldset>
<fieldset><legend><span>02</span>紹介内容</legend><div class="admin-form-grid"><label class="admin-span-2">キャッチコピー <b>*</b><input name="catchcopy" value="<?=e($team['catchcopy'])?>" required></label><label class="admin-span-2">作品説明 <b>*</b><textarea name="description" rows="5" required><?=e($team['description'])?></textarea></label><label>見どころ<textarea name="highlights" rows="5"><?=e(teamAdminListText($team['highlights']))?></textarea></label><label>操作方法<textarea name="controls" rows="5"><?=e(teamAdminListText($team['controls']))?></textarea></label><label class="admin-span-2">動画URL<input type="url" name="video_url" value="<?=e($team['video_url'])?>"></label></div></fieldset>
<fieldset><legend><span>03</span>作品QRコード</legend><div class="qr-preview-grid"><div data-qr-value="<?=e($teamQrUrl)?>"></div><div><label>固定URL<input value="<?=e($teamQrUrl)?>" readonly></label><p class="form-note">変更を保存するとQRコードが自動で有効になります。</p><button type="button" class="button button-outline" data-qr-download>PNGをダウンロード</button><button type="button" class="button button-outline" data-qr-print>印刷する</button></div></div></fieldset>
<div class="admin-form-actions"><p>作品情報とQRコードを同時に保存します。</p><button class="button button-primary" name="save_team" value="1">変更を保存する →</button></div></form><?php else:?><div class="admin-empty"><span>WORK DATA</span><h2>編集する作品を選択</h2><p>左の一覧から作品を選んでください。</p></div><?php endif;?></div></div></section><script src="<?=e(url('assets/vendor/qrcode.min.js'))?>"></script><script src="<?=e(url('assets/qr-admin.js'))?>"></script></main></body></html>
